/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Er model module.
 * @module model/Er
 * @version 1.0.0
 */
class Er {
    /**
     * Constructs a new <code>Er</code>.
     * @alias module:model/Er
     * @param er {Number} 
     */
    constructor(er) { 
        
        Er.initialize(this, er);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, er) { 
        obj['er'] = er;
    }

    /**
     * Constructs a <code>Er</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Er} obj Optional instance to populate.
     * @return {module:model/Er} The populated <code>Er</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Er();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('er')) {
                obj['er'] = ApiClient.convertToType(data['er'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Er.prototype['_id'] = undefined;

/**
 * @member {Number} er
 */
Er.prototype['er'] = undefined;






export default Er;

